// vm.hpp -- QuakeC program runtime structures
#pragma once

#include <ostream>
#include <EASTL/array.h>
#include <EASTL/string_view.h>
#include "pr_comp.hpp"  // defs shared with qcc
#include "progdefs.hpp" // generated by program cdefs

typedef union eval_s {
    string_t string;
    float _float;
    float vector[3];
    func_t function;
    int _int;
    int edict;
} eval_t;

constexpr int MAX_ENT_LEAFS = 16;

typedef struct edict_s {
    qboolean free;
    link_t area; // linked to a division node or leaf

    int num_leafs;
    short leafnums[MAX_ENT_LEAFS];

    entity_state_t baseline;

    float freetime; // sv.time when the object was freed
    entvars_t v;    // C exported fields from progs
                    // other fields from progs come immediately after
} edict_t;

#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l, edict_t, area)

//============================================================================

namespace VM {

extern dprograms_t* progs;
extern dfunction_t* pr_functions;
extern char* pr_strings;
extern ddef_t* pr_globaldefs;
extern ddef_t* pr_fielddefs;
extern dstatement_t* pr_statements;
extern globalvars_t* pr_global_struct;
extern float* pr_globals; // same as pr_global_struct

extern int pr_edict_size; // in bytes

//============================================================================

void PR_Init();

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs();

string_t PR_SetString(const char* str);
inline string_t PR_SetString(eastl::string_view str) { return PR_SetString(str.data()); }
[[nodiscard]] char* PR_GetString(string_t handle);
string_t PR_CreateString(int size, char** out_ptr);

void PR_Profile_f();

[[nodiscard]] edict_t* ED_Alloc();
void ED_Free(edict_t* ed);

string_t ED_NewString(const char* source);
inline string_t ED_NewString(eastl::string_view source) { return ED_NewString(source.data()); }

void ED_Print(edict_t* ed);
void ED_Write(std::ostream& f, edict_t* ed);
char* ED_ParseEdict(char* data, edict_t* ent);

void ED_WriteGlobals(std::ostream& f);
void ED_ParseGlobals(char* data);

void ED_LoadFromFile(char* data);

[[nodiscard]] edict_t* EDICT_NUM(int n);
[[nodiscard]] int NUM_FOR_EDICT(edict_t* e);

#define NEXT_EDICT(e) ((edict_t*)((byte*)e + pr_edict_size))

#define EDICT_TO_PROG(e) ((byte*)e - (byte*)sv.edicts)
#define PROG_TO_EDICT(e) ((edict_t*)((byte*)sv.edicts + e))

//============================================================================

#define G_FLOAT(o) (pr_globals[o])
#define G_INT(o) (*(int*)&pr_globals[o])
#define G_EDICT(o) ((edict_t*)((byte*)sv.edicts + *(int*)&pr_globals[o]))
#define G_EDICTNUM(o) NUM_FOR_EDICT(G_EDICT(o))
#define G_VECTOR(o) (&pr_globals[o])
#define G_STRING(o) (PR_GetString(*(string_t*)&pr_globals[o]))
#define G_FUNCTION(o) (*(func_t*)&pr_globals[o])

#define E_FLOAT(e, o) (((float*)&e->v)[o])
#define E_INT(e, o) (*(int*)&((float*)&e->v)[o])
#define E_VECTOR(e, o) (&((float*)&e->v)[o])
#define E_STRING(e, o) (PR_GetString(*(string_t*)&((float*)&e->v)[o]))

extern eastl::array<int, 8> type_size;

typedef void (*builtin_t)(void);
extern builtin_t* pr_builtins;
extern int pr_numbuiltins;

extern int pr_argc;

extern qboolean pr_trace;
extern dfunction_t* pr_xfunction;
extern int pr_xstatement;

extern unsigned short pr_crc;

[[noreturn]] void PR_RunError(const char* error, ...);

void ED_PrintEdicts();
void ED_PrintNum(int ent);

[[nodiscard]] eval_t* GetEdictFieldValue(edict_t* ed, const char* field);
inline eval_t* GetEdictFieldValue(edict_t* ed, eastl::string_view field) { return GetEdictFieldValue(ed, field.data()); }

} // namespace VM

